FROM docker.io/cachyos/cachyos:latest

RUN pacman -Syu --noconfirm \
    neovim \
    tmux \
    zsh \
    opencode \
    ripgrep \
    fzf && \
  pacman -Scc --noconfirm && \
  useradd -m -s /usr/bin/zsh devbox

USER devbox
WORKDIR /home/devbox

RUN --mount=type=bind,target=dotfiles \
  cp dotfiles/zsh/zshrc.zsh .zshrc && \
  cp dotfiles/tmux/tmux.conf .tmux.conf && \
  cp dotfiles/git/gitconfig .gitconfig && \
  mkdir -p .config/nvim && \
  cp dotfiles/nvim/init.lua .config/nvim/init.lua && \
  cp -r dotfiles/nvim/pack .config/nvim/pack && \
  cd .config/nvim/pack/omnimike/start/telescope-fzf-native.nvim && \
  make && \
  cd - && \
  mkdir -p .config/opencode && \
  cp dotfiles/opencode/opencode.jsonc .config/opencode/opencode.jsonc && \
  cp dotfiles/opencode/tui.json .config/opencode/tui.json && \
  mkdir /home/devbox/ws

CMD zsh
