set global ui_options ncurses_assistant=none
source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/fzf.kak"
plug "mawww/kak-lsp" do %{
  cargo build --release --locked
  cargo install --force
}

map global normal <space> , -docstring 'leader'
map global user s ': w<ret>' -docstring 'save'
map global user z ': wq<ret>' -docstring 'save and quit'
map global user q ': q<ret>' -docstring 'quit'
map global user p ': fzf-mode<ret>'
